remote_theme: abhinavs/moonwalk

favicon: "favicon-32x32.png" # relative path to site's favicon

theme_config:
  appearance: "dark" # can be "light", "dark" or "auto"
  appearance_toggle: true # if appearance can be switched by user
  show_navbar: false
  show_footer: false 
