---
# General Dependencies
general:
  dependencies:
    apt:
      - apt-transport-https=1.* # known good with 1.6.6ubuntu0.1 all
      - ca-certificates=20180409 # known good with 20180409
      - curl=7.* # known good with 7.58.0-2ubuntu3.5
      - gnupg-agent=2.* # known good with 2.2.4-1ubuntu1.2
      - python3-apt=1.* # known good with 1.6.3
      - python3-pip=9.* # known good with 9.0.1-2.3~ubuntu1
      - python3-setuptools=39.* # known good with 39.0.1-2
      - software-properties-common=0.96.24.32.7 # known good with 0.96.24.32.7
      - git
      - golang
    pip:
      - docker>=3.7.0 # known good with 3.7.0
